import math

class Hyperparameters:
    INIT_SEED = 12235155
    VALIDATION_SEED = 12343124234
    MAD_NO_OF_SAMPLES = 50
    PARTITIONING_EPSILON = 0.1
    DIAMETER_THRESHOLD_TPCH_PRICE = 50
    DIAMETER_THRESHOLD_TPCH_QUANTITY = 5
    DIAMETER_THRESHOLD_TPCH_TAX = 0.05
    DIAMETER_THRESHOLD_PORTFOLIO_PRICE = 5
    DIAMETER_THRESHOLD_PORTFOLIO_GAIN = 10
    DIAMETER_THRESHOLD_GARCH_PRICE = 5
    DIAMETER_THRESHOLD_GARCH_GAIN = 10
    DIAMETER_THRESHOLD_GBM_PRICE = 5
    DIAMETER_THRESHOLD_GBM_GAIN = 10
    SIZE_THRESHOLD = 100000
    INIT_NO_OF_SCENARIOS = 100
    INIT_NO_OF_SUMMARIES = 1
    NO_OF_VALIDATION_SCENARIOS = 1000000
    SAMPLING_TOLERANCE = math.inf
    APPROXIMATION_BOUND = 0.1
    BISECTION_THRESHOLD = 0.1
    NO_OF_RANDOM_WALKS = 100000
    MAX_TUPLES_IN_PACKAGE = 30
    NO_OF_HIST_BINS = 2000
    HIST_ERROR = 0.1
    ALPHA_REDUCTION = 0.05
    MAX_OPT_SCENARIOS_IN_PRACTICE = 2000